# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_entry_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
